name: Main Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test the Application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer Install
        run: |
          composer install

      - name: Create .env
        run: |
          cp .env.ci .env

      - name: Generate the key
        run: |
          php artisan key:generate

      - name: Migrate the Database
        run: |
          php artisan migrate

      - name: Run Unit Testing
        run: |
          php artisan test